import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/contexts/auth/auth.context'
import { DataServiceProvider } from '@/contexts/service/data.context'
import { Login } from '@/app/_components/login'
import { LoginModalProvider } from '@/components/app/login/context/login-modal.context'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const queryClient = new QueryClient()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <DataServiceProvider>
            <LoginModalProvider>
              <QueryClientProvider client={queryClient}>
                <Login />
                {children}
              </QueryClientProvider>
            </LoginModalProvider>
          </DataServiceProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
